/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by @uni-ku/bundle-optimizer
declare module '*?async' {
  const component: any
  export = component
}
declare module './components/BarChart.vue?async' {
  const component: typeof import('./components/BarChart.vue')
  export = component
}
declare module './components/DonutChart.vue?async' {
  const component: typeof import('./components/DonutChart.vue')
  export = component
}
declare module './components/FunnelChart.vue?async' {
  const component: typeof import('./components/FunnelChart.vue')
  export = component
}
declare module './components/GaugeChart.vue?async' {
  const component: typeof import('./components/GaugeChart.vue')
  export = component
}
declare module './components/LineChart.vue?async' {
  const component: typeof import('./components/LineChart.vue')
  export = component
}
declare module './components/LiquidFillChart.vue?async' {
  const component: typeof import('./components/LiquidFillChart.vue')
  export = component
}
declare module './components/MiniLineChart.vue?async' {
  const component: typeof import('./components/MiniLineChart.vue')
  export = component
}
declare module './components/PieChart.vue?async' {
  const component: typeof import('./components/PieChart.vue')
  export = component
}
declare module './components/RadarChart.vue?async' {
  const component: typeof import('./components/RadarChart.vue')
  export = component
}
declare module './components/ScatterChart.vue?async' {
  const component: typeof import('./components/ScatterChart.vue')
  export = component
}
declare module './components/StackedBarChart.vue?async' {
  const component: typeof import('./components/StackedBarChart.vue')
  export = component
}
declare module '@/subEcharts/components/BarChart.vue?async' {
  const component: typeof import('@/subEcharts/components/BarChart.vue')
  export = component
}
declare module '@/subEcharts/components/DonutChart.vue?async' {
  const component: typeof import('@/subEcharts/components/DonutChart.vue')
  export = component
}
declare module '@/subEcharts/components/FunnelChart.vue?async' {
  const component: typeof import('@/subEcharts/components/FunnelChart.vue')
  export = component
}
declare module '@/subEcharts/components/GaugeChart.vue?async' {
  const component: typeof import('@/subEcharts/components/GaugeChart.vue')
  export = component
}
declare module '@/subEcharts/components/LineChart.vue?async' {
  const component: typeof import('@/subEcharts/components/LineChart.vue')
  export = component
}
declare module '@/subEcharts/components/LiquidFillChart.vue?async' {
  const component: typeof import('@/subEcharts/components/LiquidFillChart.vue')
  export = component
}
declare module '@/subEcharts/components/MiniLineChart.vue?async' {
  const component: typeof import('@/subEcharts/components/MiniLineChart.vue')
  export = component
}
declare module '@/subEcharts/components/PieChart.vue?async' {
  const component: typeof import('@/subEcharts/components/PieChart.vue')
  export = component
}
declare module '@/subEcharts/components/ScatterChart.vue?async' {
  const component: typeof import('@/subEcharts/components/ScatterChart.vue')
  export = component
}
declare module '@/subEcharts/components/StackedBarChart.vue?async' {
  const component: typeof import('@/subEcharts/components/StackedBarChart.vue')
  export = component
}
declare module '@/subEcharts/components/RadarChart.vue?async' {
  const component: typeof import('@/subEcharts/components/RadarChart.vue')
  export = component
}
declare module '@/subEcharts/echarts/components/BarChart.vue?async' {
  const component: typeof import('@/subEcharts/echarts/components/BarChart.vue')
  export = component
}
declare module '@/subEcharts/echarts/components/DonutChart.vue?async' {
  const component: typeof import('@/subEcharts/echarts/components/DonutChart.vue')
  export = component
}
declare module '@/subEcharts/echarts/components/FunnelChart.vue?async' {
  const component: typeof import('@/subEcharts/echarts/components/FunnelChart.vue')
  export = component
}
declare module '@/subEcharts/echarts/components/GaugeChart.vue?async' {
  const component: typeof import('@/subEcharts/echarts/components/GaugeChart.vue')
  export = component
}
declare module '@/subEcharts/echarts/components/LineChart.vue?async' {
  const component: typeof import('@/subEcharts/echarts/components/LineChart.vue')
  export = component
}
declare module '@/subEcharts/echarts/components/LiquidFillChart.vue?async' {
  const component: typeof import('@/subEcharts/echarts/components/LiquidFillChart.vue')
  export = component
}
declare module '@/subEcharts/echarts/components/MiniLineChart.vue?async' {
  const component: typeof import('@/subEcharts/echarts/components/MiniLineChart.vue')
  export = component
}
declare module '@/subEcharts/echarts/components/PieChart.vue?async' {
  const component: typeof import('@/subEcharts/echarts/components/PieChart.vue')
  export = component
}
declare module '@/subEcharts/echarts/components/ScatterChart.vue?async' {
  const component: typeof import('@/subEcharts/echarts/components/ScatterChart.vue')
  export = component
}
declare module '@/subEcharts/echarts/components/StackedBarChart.vue?async' {
  const component: typeof import('@/subEcharts/echarts/components/StackedBarChart.vue')
  export = component
}
declare module '@/subEcharts/echarts/components/RadarChart.vue?async' {
  const component: typeof import('@/subEcharts/echarts/components/RadarChart.vue')
  export = component
}
